# playbooks/ctrl.yaml
- hosts: all
  # connection: local
  become: yes
  tasks:
    - name: Initialize Kubernetes control plane
      command: >
        kubeadm init --apiserver-advertise-address=192.168.57.100 \
        --pod-network-cidr=10.244.0.0/16 \
        --ignore-preflight-errors=NumCPU,Mem
      args:
        creates: /etc/kubernetes/admin.conf
      register: kube_init

    - name: Extract join command
      set_fact:
        join_cmd: "{{ kube_init.stdout_lines | select('search', 'kubeadm join') | list | first | trim }}"

    - name: Fix admin.conf permissions
      become: yes
      file:
        path: /etc/kubernetes/admin.conf
        mode: 0644

    - name: Ensure .kube directory exists
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Set up kubeconfig for vagrant user
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        owner: vagrant
        group: vagrant
        mode: 0644
        remote_src: yes  

    - name: Wait for Kubernetes API to be ready
      command: kubectl get nodes --kubeconfig /etc/kubernetes/admin.conf
      register: api_check
      until: api_check.rc == 0
      retries: 10
      delay: 10

    - name: Install Flannel network plugin
      command: >
        kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
        --validate=false
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf